FROM registry.yaltik.net/odoo:yaltikbase12
MAINTAINER Yaltik - Fabien Bourgeois <fabien@yaltik.com>

# Locales
USER root
RUN apt update && apt install -y locales locales-all
USER odoo

# Configuration
RUN  git config --global user.email "bot@mokatourisme.fr" && \
      git config --global user.name "MOKA Bot"

# External code
WORKDIR /opt/odoo/extra-addons

# OCA
RUN git clone -b 12.0 https://github.com/OCA/community-data-files && \
      git clone -b 12.0 https://github.com/OCA/l10n-france && \
      git clone -b 12.0 https://github.com/OCA/queue && \
      git clone -b 12.0 https://github.com/OCA/partner-contact && \
      git clone -b 12.0 https://github.com/OCA/social && \
      git clone -b 12.0 https://github.com/OCA/server-brand && \
      git clone -b 12.0 https://github.com/OCA/web && \
      git clone -b 12.0 https://github.com/OCA/account-financial-tools && \
      git clone -b 12.0 https://github.com/OCA/account-financial-reporting && \
      git clone -b 12.0 https://github.com/OCA/website && \
      git clone -b 12.0 https://github.com/OCA/contract && \
      git clone -b 12.0 https://github.com/OCA/bank-statement-import && \
      git clone -b 12.0 https://github.com/OCA/mis-builder && \
      git clone -b 12.0 https://github.com/OCA/pos && \
      git clone -b 12.0 https://github.com/OCA/project && \
      git clone -b 12.0 https://github.com/OCA/sale-reporting && \
      git clone -b 12.0 https://github.com/OCA/sale-workflow && \
      git clone -b 12.0 https://github.com/OCA/margin-analysis && \
      git clone -b 12.0 https://github.com/OCA/reporting-engine && \
      git clone -b 12.0 https://github.com/OCA/product-variant && \
      git clone -b 12.0 https://github.com/OCA/e-commerce

# Module + PR 89 replaced by by moka_custom
RUN rm -r /opt/odoo/extra-addons/sale-reporting/sale_layout_category_hide_detail

RUN cd /opt/odoo/extra-addons/product-variant/ && \
      git fetch origin pull/171/head:mokatmp && \
      git cherry-pick 37d0526cd26a26bfe88b9ed1f39d2a14ced926fa

RUN cd /opt/odoo/extra-addons/account-financial-tools/ && \
      git fetch origin pull/872/head:mokatmp && \
      git cherry-pick 14a2c1b8c1d5b696a7be490f8df3219037d5fec4

# MUK
RUN git clone -b 12.0 https://github.com/muk-it/muk_base && \
      git clone -b 12.0 https://github.com/muk-it/muk_misc && \
      git clone -b 12.0 https://github.com/muk-it/muk_web && \
      git clone -b 12.0 https://github.com/muk-it/muk_website

# Others
RUN git clone -b 12.0 https://github.com/JayVora-SerpentCS/SerpentCS_Contributions
RUN git clone -b 12.0 https://github.com/druidoo/druidoo-addons
RUN git clone -b 12.0 https://github.com/Openworx/backend_theme
RUN git clone -b 12.0 https://github.com/gityopie/odoo-addons gityopie-odoo-addons

WORKDIR /opt/odoo

# Addons dependencies
RUN .local/bin/pip3 install --user openupgradelib

# Custom code
ENV GITLAB_USER mokabot%40mokatourisme.fr
ENV GITLAB_PASS MoK%40BoT2020

RUN mkdir -p /opt/odoo/extra-addons/moka
WORKDIR /opt/odoo/extra-addons/moka
# Test branches for MOKA code
RUN git clone --depth 1 -b 12.0-dev https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/moka_fr/moka-billetterie.git moka_billetterie
RUN git clone --depth 1 -b 12.0-dev https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/moka_fr/moka-depot-vente.git moka_depot_vente
WORKDIR /opt/odoo/extra-addons
RUN git clone --depth 1 -b 12.0_dev https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/moka_fr/moka.git moka_extra && mv moka_extra/custom moka_custom && mv moka_extra/thirdparty moka_thirdparty && rm -rf moka_extra

# Custom configuration (MUK)

WORKDIR /opt/odoo

COPY launch.sh /opt/odoo/launch.sh
