FROM registry.yaltik.net/odoo:moka12
LABEL maintainer="ivan.todorovich@gmail.com"
ARG GITHUB_USER
ARG GITHUB_TOKEN
COPY repos.prod.yml $RESOURCES/repos.yml
RUN autoaggregate --install -c $RESOURCES/repos.yml -o $SOURCES/repositories
