FROM registry.yaltik.net/odoo:yaltikbase12
MAINTAINER Yaltik - Fabien Bourgeois <fabien@yaltik.com>

# External code
WORKDIR /opt/odoo/extra-addons

RUN git clone -b 12.0 https://github.com/OCA/community-data-files && \
      git clone -b 12.0 https://github.com/OCA/l10n-france && \
      git clone -b 12.0 https://github.com/OCA/queue && \
      git clone -b 12.0 https://github.com/OCA/partner-contact && \
      git clone -b 12.0 https://github.com/OCA/social && \
      git clone -b 12.0 https://github.com/OCA/server-brand && \
      git clone -b 12.0 https://github.com/OCA/web && \
      git clone -b 12.0 https://github.com/OCA/account-financial-tools && \
      git clone -b 12.0 https://github.com/OCA/account-financial-reporting && \
      git clone -b 12.0 https://github.com/OCA/website && \
      git clone -b 12.0 https://github.com/OCA/contract && \
      git clone -b 12.0 https://github.com/OCA/bank-statement-import && \
      git clone -b 12.0 https://github.com/OCA/mis-builder && \
      git clone -b 12.0 https://github.com/OCA/pos && \
      git clone -b 12.0 https://github.com/OCA/project && \
      git clone -b 12.0 https://github.com/OCA/sale-reporting && \
      git clone -b 12.0 https://github.com/OCA/sale-workflow && \
      git clone -b 12.0 https://github.com/OCA/margin-analysis && \
      git clone -b 12.0 https://github.com/OCA/reporting-engine

RUN git clone -b 12.0 https://github.com/muk-it/muk_base && \
      git clone -b 12.0 https://github.com/muk-it/muk_misc && \
      git clone -b 12.0 https://github.com/muk-it/muk_web && \
      git clone -b 12.0 https://github.com/muk-it/muk_website

RUN git clone -b 12.0 https://github.com/JayVora-SerpentCS/SerpentCS_Contributions

RUN git clone -b 12.0 https://github.com/druidoo/druidoo-addons

WORKDIR /opt/odoo

# Addons dependencies
RUN .local/bin/pip3 install --user openupgradelib

# Custom code
ENV GITLAB_USER mokabot%40mokatourisme.fr
ENV GITLAB_PASS MoK%40BoT2020

RUN mkdir -p /opt/odoo/extra-addons/moka
WORKDIR /opt/odoo/extra-addons/moka
# Test branches for MOKA code
RUN git clone --depth 1 -b 12.0-dev https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/moka_fr/moka-billetterie.git moka_billetterie
RUN git clone --depth 1 -b 12.0-dev https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/moka_fr/moka-depot-vente.git moka_depot_vente

# Custom configuration (MUK)

WORKDIR /opt/odoo

COPY launch.sh /opt/odoo/launch.sh
